### ISSUE TITLE
SChinese Language

### ISSUE THREAD

**Issue by TianMengLucky** [SubDekoKiyo/UltimateMods#3]
I have added SChinese language to the form if you need it. Here is the file URL:https://github.com/MC-AS-Huier/UltimateMods/blob/main/Translate.xlsx
（必要であれば、フォームにSChinese言語を追加しています。 以下は、ファイルのURL:https://github.com/MC-AS-Huier/UltimateMods/blob/main/Translate.xlsx。）

**Comment by DekoKiyo** [comment]
Thank you for your translation.
Sorry, SChinese translation already exists.
Therefore, I will decline.
