### ISSUE TITLE
Request indonesian language

### ISSUE THREAD

**Issue by pampampam999** [SubDekoKiyo/UltimateMods#4]
Hello im pampam and I'm glad if I can contribute to translate in Indonesian language

**Comment by DekoKiyo** [comment]
There is no Indonesian language support for AmongUs, is that okay?
But, maybe can supported in mod...
Do you have any Discord Account?

**Comment by Kiwatani** [comment]
My question is...
How many people do you know who play AmongUs?

**Comment by pampampam999** [comment]
pampampam#2571
